[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "scons>=3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "node-and-date"

[project]
name = "Cassiopee"
authors = [
  { name="ONERA", email="christophe.benoit@onera.fr" },
]
license = {text="GPLv3"}
description = "Computational Fluid Dynamics pre- and post-processing python modules"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: Unix",
  "Operating System :: Microsoft :: Windows",
  "Topic :: Scientific/Engineering :: Physics"
]

[project.dependencies]
numpy = ">=1.23.3"
mpi4py = ">=3.1.3"
scons = ">=4.4.0"
KCore = ">=4.0"
XCore = ">=4.0"
Converter = ">=4.0"
Geom = ">=4.0"
Transform = ">=4.0"
Generator = ">=4.0"
Post = ">=4.0"
Initiator = ">=4.0"
Connector = ">=4.0"
Distributor2 = ">=4.0"
Dist2Walls = ">=4.0"
RigidMotion = ">=4.0"
Compressor = ">=4.0"
Modeler = ">=4.0"
Intersector = ">=4.0"
Apps = ">=4.0"
CPlot = ">=4.0"

[project.optional-dependencies]

[project.urls]
Homepage = "https://github.com/onera/Cassiopee"
Issues = "https://github.com/onera/Cassiopee/issues"
