name: docker

on:
  push:
    tags:
      - 'v*'
#    branches:
#      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Print GitHub context
        run: |
          echo "Ref Name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: cassiopee486/cassiopee:${{ github.ref_name }}

